/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package polkammart;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author oryza
 */
public class Pegawai extends javax.swing.JInternalFrame {

    /**
     * Creates new form Pegawai
     */
    private DefaultTableModel model;
    Object[ ] obj;
    public Pegawai() {
        initComponents();
       
        
        AmbilData();
        this.setTitle("Data Karyawan");
        
    }
public void AmbilData(){
    
        model=new DefaultTableModel();
        jTable2.setModel(model);
        model.addColumn("NO");
        model.addColumn("Nama");
        model.addColumn("Level Pengguna");
        
    model.getDataVector( ).removeAllElements( );
    model.fireTableDataChanged( );
    int i=1;
    try{
    //membuat statemen pemanggilan data pada table tblGaji dari database
    Statement stat = (Statement) Koneksi.getKoneksi().createStatement( );
    
    String sql = "Select * from pengguna, level where pengguna.level=level.no";
    ResultSet res = stat.executeQuery(sql);
    //penelusuran baris pada tabel tblGaji dari database
    while(res.next ()){
    obj= new Object[3];
    
    obj[0] =i;
    obj[1] = res.getString("nama");
    obj[2] = res.getString("nama_lvl");
    
    model.addRow(obj);
    i++;
}
}catch(SQLException err){
JOptionPane.showMessageDialog(null, err.getMessage() );
}
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rubah = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 255, 51));
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rubah.setBackground(new java.awt.Color(0, 0, 0));
        rubah.setFont(new java.awt.Font("Orator Std", 3, 18)); // NOI18N
        rubah.setText("Rubah");
        rubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rubahActionPerformed(evt);
            }
        });
        getContentPane().add(rubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 420, 30));

        tambah.setBackground(new java.awt.Color(0, 0, 0));
        tambah.setFont(new java.awt.Font("Orator Std", 3, 18)); // NOI18N
        tambah.setText("Tambah");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 420, 30));

        hapus.setBackground(new java.awt.Color(0, 0, 0));
        hapus.setFont(new java.awt.Font("Orator Std", 3, 18)); // NOI18N
        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 420, 30));

        jTable2.setBackground(new java.awt.Color(255, 255, 0));
        jTable2.setForeground(new java.awt.Color(255, 255, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 520, 130));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\sus\\foto\\Komunikasikan-resiko.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 520, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        TambahPegawai tamb=new TambahPegawai();
        this.getParent().add(tamb);
        tamb.setVisible(true);
        tamb.setSize(this.getWidth(),this.getHeight());
        
        tamb.setLocation(0,0);
        this.setVisible(false);
    }//GEN-LAST:event_tambahActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        try{
            int column = 1;
            int selectedRowIndex=jTable2.getSelectedRow();
            String value = jTable2.getModel().getValueAt(selectedRowIndex, column).toString();
            JOptionPane.showMessageDialog(null, value);
            String query="Delete from pengguna where nama='"+value+"'";
//            JOptionPane.showMessageDialog(null, value);
            //membuat statemen pemanggilan data pada table tblGaji dari database
            Statement stat = (Statement) Koneksi.getKoneksi().createStatement();
            stat.executeUpdate(query);
            AmbilData();          
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void rubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rubahActionPerformed
        // TODO add your handling code here:
        int column = 1;
        
        try{
           int selectedRowIndex=jTable2.getSelectedRow();
            
            if(selectedRowIndex<-1){
            JOptionPane.showMessageDialog(null, "Silahkan Pilih Data Terlebih Dahulu");
        }else{
            String value = jTable2.getModel().getValueAt(selectedRowIndex, column).toString();
            GetDataPengguna.setUserLogin(value);
            RubahPegawai rbh=new RubahPegawai();
            this.getParent().add(rbh);
            rbh.setVisible(true);
            rbh.setSize(this.getWidth(),this.getHeight());
            rbh.setLocation(0,0);
            this.setVisible(false);
        }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_rubahActionPerformed

    public void refresh(){
        this.AmbilData();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton rubah;
    private javax.swing.JButton tambah;
    // End of variables declaration//GEN-END:variables

}
